apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cta-ingress-backend
  namespace: cta-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - cta-backend.com
    secretName: cta-be-tls
  rules:
  - host: cta-backend.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cta-backend-svc
            port:
              number: 4000
